### ISSUE TITLE
AttributeError: 'signal' object has no attribute 'connect'

### ISSUE THREAD

**Issue by prehensile** [zyga/morris#1]
I've defined a signal like so:

**somefile.py**:

```
import morris

@Signal.define
def token_saved( pth_token ):
    pass
```

**anotherfile.py**

```
import somefile

somefile.token_saved.connect( on_token )
```

But I'm getting the following error when calling `connect`:

```
AttributeError: 'signal' object has no attribute 'connect'
```

Is there an issue connecting listeners across modules, or have I misread the docs in some way / set up my signal wrong?

**Comment by zyga** [comment]
Yep, mistake on my part. It works well if you put signals into classes. I'll fix that and issue a small release.

**Comment by zyga** [comment]
This is now fixed, enjoy
